import React from 'react'

function Error() {
  return (
    <div>
  page not found ...............
  page not found ...............
  page not found ...............
  <h4 >page not found ...............
  page not found ...............
  page not found ...............page not found ...............
  page not found ...............
  page not found ...............page not found ...............
  page not found ...............
  page not found ...............</h4>
  <h1>page not found ...............
  page not found ...............
  page not found ...............</h1>
    </div>
  )
}

export default Error
